import tkinter as tk
root=tk.Tk()
root.geometry("800x800")
root.config(bg="light green")
root.title("REGISTRATION FORM")
button1=tk.Button(root,text="SUBMIT")
label1=tk.Label(root,text="Name")
label2=tk.Label(root,text="Course")
label3=tk.Label(root,text="Semester")
label4=tk.Label(root,text="Form.No")
label5=tk.Label(root,text="Contact.No")
label6=tk.Label(root,text="Email Id")
label7=tk.Label(root,text="Address")


entery1=tk.Entry(root,text="Ankit Rai")
entery2=tk.Entry(root,text="B.Tech")
entery3=tk.Entry(root,text="4TH")
entery4=tk.Entry(root,text="123")
entery5=tk.Entry(root,text="8940*****7")
entery6=tk.Entry(root,text="abcd@gmail.com")
entery7=tk.Entry(root,text="new colony, Lucknow")


label1.place(x=214,y=205)
label2.place(x=214,y=243)
label3.place(x=214,y=284)
label4.place(x=214,y=325)
label5.place(x=214,y=366)
label6.place(x=214,y=407)
label7.place(x=214,y=448)
button1.place(x=619,y=579)

entery1.place(x=265,y=207)
entery2.place(x=265,y=243)
entery3.place(x=278,y=286)
entery4.place(x=288,y=327)
entery5.place(x=308,y=365)
entery6.place(x=277,y=406)
entery7.place(x=277,y=447)

label1=tk.Label(root,bg="light green")
label2=tk.Label(root,bg="light green")
label3=tk.Label(root,bg="light green")
label4=tk.Label(root,bg="light green")
label5=tk.Label(root,bg="light green")
label6=tk.Label(root,bg="light green")
label7=tk.Label(root,bg="light green")

root.mainloop()